# Generated by Django 3.0.8 on 2020-10-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_auto_20200912_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('img', models.CharField(max_length=2000)),
                ('subs', models.IntegerField()),
                ('views', models.IntegerField()),
                ('videos', models.IntegerField()),
                ('channel_id', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
